pruebas_index:
    path: /pruebas/{lang}/{name}/{page}
    defaults: {_controller: AppBundle:Pruebas:Index, lang:es,name:contenido_por_defecto, page:1}
    methods: [GET, POST]
    requirements:
        name: "[a-zA-Z]*"
        page: \d+
        lang: es|en|fr