AppBundle\Entity\Curso:
    properties:
        titulo:
            - NotBlank: {message: "El titulo no puede estar en blanco"}
            - Length:
                min: 2
                minMessage: "El titulo debe de contener mas de dos caracteres"
        descripcion:
            - NotBlank: {message: "La descripcion no puede estar en blanco"}
        precio:
            - Type:
                type: numeric
                message: "El precio tiene que ser numerico"